src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_completed;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    public function __construct()
    {
        $this->is_completed = false;
        $this->createdAt= new \DateTime();
        $this->updatedAt= new \DateTime();
    }

    /**
     * @ORM\PreUpdate()
     */
    public function preUpdate()
    {
        $this->updatedAt= new \DateTime();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIsCompleted(): ?bool
    {
        return $this->is_completed;
    }

    public function setIsCompleted(bool $is_completed): self
    {
        $this->is_completed = $is_completed;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Controller/IndexController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;

use App\Entity\Task;

class IndexController extends AbstractController
{

    public function index()
    {
    	$tasks = $this->getDoctrine()
	        ->getRepository(Task::class)
	        ->findAll();

        return $this->render('index.html.twig', [
        	'tasks' => $tasks
        ]);
    }

    public function add(Request $request)
    {
    	$entityManager = $this->getDoctrine()->getManager();

    	$task = new Task();
    	$task->setName($request->get('name'));
    	$entityManager->persist($task);
    	$entityManager->flush($task);

    	return new JsonResponse(['id' => $task->getId()]);
    }

	public function update(Task $task, Request $request)
    {
        $task->setName($request->get('name'));
        
	    $entityManager = $this->getDoctrine()->getManager();
	    $entityManager->persist($task);
    	$entityManager->flush($task);

        return new JsonResponse([]);
    }

    public function delete(Task $task, Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($task);
        $entityManager->flush();

        return new JsonResponse([]);
    }

    public function complete(Task $task, Request $request)
    {
		$completed = $request->get('isComplete') == "true" ? 1 : 0;
        $task->setIsCompleted($completed);
        
	    $entityManager = $this->getDoctrine()->getManager();
	    $entityManager->persist($task);
    	$entityManager->flush($task);

        return new JsonResponse([]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/index.html.twig
<!DOCTYPE html>
<html>

<head>
	<title>ToDo List</title>
	<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<link rel="stylesheet" href="/css/style.css">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.materialdesignicons.com/2.2.43/css/materialdesignicons.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pretty-checkbox/3.0.3/pretty-checkbox.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/0.4.0/modern-normalize.css">
</head>

<body>
	<div id="hero" class="hero">
		<h1 class="title">Список задач</h1>
		<div id="todoApp" class="todo-app">
			<div id="todoMenu1" class="todo-menu-1">
				<button id="toggleAll" class="toggle-all" aria-label="Выбрать все задачи">
					<span class="rotate">&#x276F;</span>
				</button>
				<input @keyup.enter="addTask" v-model="newTask" 
					   id="addTodoTextInput" class="add-todo-text-input"
					   type="text" placeholder="Чем хотите заняться?" 
					   aria-label="Введите название задачи" autofocus
					   minlength="1"
				>
			</div>
			<ul id="todos" class="todos" aria-label="Список задач">
				<li class="todo task-item" v-for="task, i in tasks">
					<div class="pretty p-icon p-round">
						<input type="checkbox" class="checkbox" v-on:change="event => completeTask(event, i)" v-bind:checked="task.isComplete">
						<div class="state">
							<i class="icon mdi mdi-check mdi-18px"></i>
							<label></label>
						</div>
					</div>
					<label v-bind:class="{completed: task.isComplete}" class="todo-text" contenteditable="true" @blur="event => editTask(event, i)">
						{{ "{{ task.name }}" }}
					</label>
					<button	class="delete-button" v-on:click="deleteTask(task, i)">×</button>
				</li>
			</ul>
			<div id="todoMenu2" class="todo-menu-2">
				<label id="todosLeft" class="todos-left"></label>
				<div id="todoMenu2Buttons" class="todo-menu-2-buttons">
					<input type="button" class="menu-2-button" onclick="location.href='https://google.com';" value="Репозиторий в GitLAB ">
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		var app = new Vue({
			el: '#hero',
			data: {
				newTask: "",
				tasks: [
					{% for task in tasks %}
					{
						id: {{ task.id }},
						name: `{{ task.name }}`,
						isComplete: `{{ task.isCompleted }}`
					},
					{% endfor %}
				]
			},
			methods: {
				addTask: function(){
					let handler = function(response){
						this.tasks.push({
							id: response.id,
							name: this.newTask
						});
						this.newTask = "";
					};
					$.post('/tasks', {name: this.newTask}, $.proxy(handler, this));
				},
				editTask: function(event, i){
					let handler = function(response){
						Vue.set(this.tasks, i, this.tasks[i]);
					};
					if (this.tasks[i]['name'] !== event.target.innerText) {
						this.tasks[i]['name'] =	event.target.innerText;
						$.post('/tasks/' + this.tasks[i]['id'] + '/update', this.tasks[i], $.proxy(handler, this));
					}
				},
				deleteTask: function (task, i) {
					if(this.tasks[i] === task) { 
						$.post('/tasks/' + this.tasks[i]['id'] + '/delete');
					} else {
						let i = this.tasks.indexOf(task)
						$.post('/tasks/' + this.tasks[i]['id'] + '/delete');
					}
					
					this.$delete(this.tasks, i);
				},
				completeTask: function(event, i){
					let handler = function(response){
						Vue.set(this.tasks, i, this.tasks[i]);
					};

					this.tasks[i]['isComplete'] = !this.tasks[i]['isComplete'];
					$.post('/tasks/' + this.tasks[i]['id'] + '/complete', this.tasks[i], $.proxy(handler, this));
				}
			}
		});
	</script>
</body>

</html>